#!/usr/bin/sh
#curl -X GET -w "@curl-format.txt" -s 0.0.0.0:80/catalog?dosage_form=tablet
#curl -X GET -w "@curl-format.txt" -s "0.0.0.0:80/catalog?dosage_form=tablet&is_discontinued=0&pack_unit=strip"
curl -X GET -w "@curl-format.txt" -s 0.0.0.0:80/catalog?therapeutic_class=antibiotic
