#!/usr/bin/sh
curl -H "Content-Type: application/json" \
     -X POST \
     -d '{"email": "jrbautista@gmail.com","password": "Abc123!Abc123"}' \
     0.0.0.0:80/login

# curl -H "Content-Type: application/json" \
#      -X POST \
#      -d '{"email": "prueba@gmail.com","password": "Abc123!Abc123"}' \
#      0.0.0.0:80/login \
# 		 | jq
